language: python
python:
  - "3.8.7"
before_install:
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test tests/ --cov-report term-missing --cov tests/
after_success:
  - coveralls
